print("carregando função \"perguntar ao Usuario\"! ")
print("Executando...")
function perguntarAoUsuario()


print("Óla, Eu serei responsavel por criar seu formulario!")
print("qual é o seu nome?")
nome = io.read()
print("Oh! entendo, Muito Prazer em te conhecer "..nome.."!")
print("Agora irei fazer algumas perguntas para fazer um pequeno formulario seu")
print("1)qual é seu idade?: ")
idade = io.read()
print("2) E sua cidade?: ")
cidade = io.read()
print("data de nascimento: ")
nascimento = io.read()
print("Certo...Creio que seja o suficiente "..nome.."!")
print("Entao aqui esta o seu pequeno formulario =)")
print("==============O==============")
print("Nome: "..nome)
print(" ")
print("idade: "..idade)
print(" ")
print("Localizaçao aproximada: "..cidade)
print(" ")
print("Nascimento: "..tostring(nascimento))
print(" ")
print("=============o=============")
print(" ")
print("e aqui se encerra seu pequeno formulario!")
print(" ")
print("Muito obrigado por participar ^_^")
end


perguntarAoUsuario()

print("(=============0000==============)")
print("obrigado por testar minha funçao")
